### ISSUE TITLE
Future release: Create API keys using wildcards `*` in index names

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1968] opened 2022-10-25 14:37 UTC
v0.30 allows users to create an API key using a wildcard when specifying which indexes should accept the key:

```
"indexes": ["products_*"] // matches products_A, products_B, etc
```

## In need of clarification
If:
  1. I have two indexes named `products_A` and `products_B`
  2. create a key name `key_for_products` using a wildcard index `products_*`
  3. then create a new index `products_C`

Will `key_for_products` be able to access the new index? Or will the wildcard only match indexes that exist during key creation?

---

Does `products*` include an index named `products`?

## Tasks
- [ ] Update keys API reference
- [ ] Update API keys guide

## References
- issue on core: https://github.com/meilisearch/meilisearch/issues/2788
- spec: https://github.com/meilisearch/specifications/pull/189
- SMEs: @Kerollmops

**Comment by curquiza** [comment] 2022-10-25 14:40
@guimachiavelli, we might have an issue merging this PR before the end of the month, I will let you know, but maybe this is something we will include in v1, not in v0.30.0. Sorry in advance for the confusion. I'll let you know.

**Comment by curquiza** [comment] 2022-10-31 15:17
Officially not present in v0.30.0. Sorry for the confusion.

**Comment by guimachiavelli** [comment] 2022-11-02 10:51
No problem, thanks for the update!

**Comment by maryamsulemani97** [comment] 2023-03-21 11:40
closing as this is a duplicate of #2194

**Closed by maryamsulemani97** 2023-03-21 11:40 UTC
Labels: new release
