### ISSUE TITLE
Add prominent links to MeiliSearch demos

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#927] opened 2021-05-12 12:15 UTC
The ability to try out MeiliSearch quickly with a demo is valuable and should be highlighted more in the documentation.

At the very least, the homepage should feature a link to one of our best demos. We could also add the full list of links somewhere in the What is MeiliSearch section.

**Comment by maryamsulemani97** [comment] 2022-04-06 10:40
duplicate of #1272

**Closed by maryamsulemani97** 2022-04-06 10:40 UTC
Labels: P2
