### ISSUE TITLE
Analytics tracker is hanging preventing page from loading

### ISSUE THREAD

**Issue by yoDon** [meilisearch/documentation#221] opened 2020-03-24 15:30 UTC
Both the MeiliSearch.com homepage and the docs.meilisearch.com documentation are failing to load because your analytics tracker is failing to load from https://analytics.meilisearch.com/tracker.js

**Comment by bidoubiwa** [comment] 2020-03-24 16:36
Hey, thanks for your issue. I'm working on it. The problem is caused because I created an non-SSR friendly component and so during server side rendering vuepress build it into a component that takes infinity to load. 

I will update this issue as soon as the problem is fixed.

**Comment by bidoubiwa** [comment] 2020-03-24 18:01
fixed by: #220 
It should be fixed once the build has been done in the github action.

**Closed by bidoubiwa** 2020-03-24 18:01 UTC
