### ISSUE TITLE
Python code hangs - needs the 'aSampleMasterKey' API key

### ISSUE THREAD

**Issue by RGGH** [meilisearch/documentation#2499] opened 2023-06-30 13:26 UTC
https://www.meilisearch.com/docs/learn/getting_started/quick_start

The Python script never completes with the copy/paste code, might confuse beginners!

should read:

`client = meilisearch.Client('http://127.0.0.1:7700', 'aSampleMasterKey')
`

not `client = meilisearch.Client('http://localhost:7700')`

**Comment by guimachiavelli** [comment] 2023-07-03 11:46
Hi @RGGH! Thanks for creating this issue!

@meilisearch/integration-team, what do you think? None of the Quick start SDK samples use `aSampleMasterKey`, which means SDK users following this tutorial might stumble on the same problem.

**Comment by brunoocasali** [comment] 2023-07-03 11:59
@alallema does the python SDK allow starting the client with no master key?

**Comment by bidoubiwa** [comment] 2023-07-03 16:48
I think every SDK's code-sample should be updated to add `aSimpleMasterKey` to it client instantiation

This is the curl code-sample
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=id' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer aSampleMasterKey' \
  --data-binary @movies.json
```

These is the JS for example:

```
const client = new MeiliSearch({ host: 'http://localhost:7700' })
client.index('movies').addDocuments(movies)
  .then((res) => console.log(res))
```

From whose I checked, none of the samples include that apiKey in the getting started code-samples.

**Comment by brunoocasali** [comment] 2023-07-03 16:53
I don't get it sorry :/ We support the integrations to be instantiated without a key, like meilisearch itself. If this is not a bug on the Python side, why should we update the code samples?

**Comment by alallema** [comment] 2023-07-04 11:23
> @alallema does the python SDK allow starting the client with no master key?

Yes, like almost SDK I think.

>  If this is not a bug on the Python side, why should we update the code samples?

Perfect!

**Comment by brunoocasali** [comment] 2023-07-12 01:05
All the PRs were closed, so no more missing keys in the quickstart guide. @guimachiavelli I'll close this, but I think we need to trigger a new docs version to see it in production :)

**Closed by brunoocasali** 2023-07-12 01:05 UTC
